import type { ProductionProcess } from "@/features/production/production.types";

export const defaultProductionProcesses: ProductionProcess[] = [
  {
    id: "design-review",
    name: "Design Review",
    description: "Validate scans, margins, and restoration plan before release.",
    owner: "CAD team",
    capacity: 12,
    targetHours: 4,
    queue: [
      {
        id: "queue-1",
        caseId: "case-1001",
        caseProcessId: "queue-1",
        workflowStepId: "design-review",
        caseCode: "CASE-1001",
        patientName: "Maria Oliveira",
        patientDetail: "#14 Crown",
        customerName: "Bright Smile customer",
        dentistName: "Dr. Marina Cruz",
        dueDate: "2026-06-10",
        serviceName: "Crown - Zirconia",
        currentStage: "Design Review",
        status: "IN_PROGRESS",
        assignee: "Ana",
        priority: "urgent",
        progressPercent: 50,
        completedSteps: 1,
        totalSteps: 3,
        notes: "Check margin on distal side.",
      },
      {
        id: "queue-2",
        caseId: "case-1002",
        caseProcessId: "queue-2",
        workflowStepId: "design-review",
        caseCode: "CASE-1002",
        patientName: "Lucas Mendes",
        patientDetail: "#36 Implant Crown",
        customerName: "Downtown Dental",
        dentistName: "Dr. Paula Neri",
        dueDate: "2026-06-11",
        serviceName: "Implant Crown",
        currentStage: "Design Review",
        status: "READY",
        assignee: "Roberto",
        priority: "high",
        progressPercent: 0,
        completedSteps: 0,
        totalSteps: 4,
      },
    ],
  },
  {
    id: "model-prep",
    name: "Model Prep",
    description: "Print, inspect, and prepare physical models for finishing.",
    owner: "Model room",
    capacity: 9,
    targetHours: 8,
    queue: [
      {
        id: "queue-3",
        caseId: "case-1003",
        caseProcessId: "queue-3",
        workflowStepId: "model-prep",
        caseCode: "CASE-1003",
        patientName: "Helena Costa",
        patientDetail: "#11-13 Bridge",
        customerName: "Northside Dentistry",
        dentistName: "Dr. Fabio Leal",
        dueDate: "2026-06-12",
        serviceName: "Bridge - Zirconia",
        currentStage: "Model Prep",
        status: "READY",
        assignee: "Julia",
        priority: "normal",
        progressPercent: 33,
        completedSteps: 1,
        totalSteps: 3,
      },
    ],
  },
  {
    id: "ceramic-finish",
    name: "Ceramic Finish",
    description: "Layering, stain, glaze, and final esthetic inspection.",
    owner: "Ceramics",
    capacity: 7,
    targetHours: 12,
    queue: [
      {
        id: "queue-4",
        caseId: "case-1004",
        caseProcessId: "queue-4",
        workflowStepId: "ceramic-finish",
        caseCode: "CASE-1004",
        patientName: "Rafael Lima",
        patientDetail: "Veneer set",
        customerName: "Apex Dental Group",
        dentistName: "Dr. Carlos Nunes",
        dueDate: "2026-06-09",
        serviceName: "Veneer - E.max",
        currentStage: "Ceramic Finish",
        status: "IN_PROGRESS",
        assignee: "Carla",
        priority: "urgent",
        progressPercent: 75,
        completedSteps: 2,
        totalSteps: 3,
        notes: "Shade match photo attached in case record.",
      },
      {
        id: "queue-5",
        caseId: "case-1005",
        caseProcessId: "queue-5",
        workflowStepId: "ceramic-finish",
        caseCode: "CASE-1005",
        patientName: "Sofia Martins",
        patientDetail: "#21 Crown",
        customerName: "Bright Smile customer",
        dentistName: "Dr. Helena Amorim",
        dueDate: "2026-06-13",
        serviceName: "Crown - E.max",
        currentStage: "Ceramic Finish",
        status: "READY",
        assignee: "Diego",
        priority: "normal",
        progressPercent: 50,
        completedSteps: 1,
        totalSteps: 2,
      },
      {
        id: "queue-6",
        caseId: "case-1006",
        caseProcessId: "queue-6",
        workflowStepId: "ceramic-finish",
        caseCode: "CASE-1006",
        patientName: "Bruno Rocha",
        patientDetail: "Night guard",
        customerName: "Downtown Dental",
        dentistName: "Dr. Paula Neri",
        dueDate: "2026-06-14",
        serviceName: "Night Guard",
        currentStage: "Ceramic Finish",
        status: "READY",
        assignee: "Carla",
        priority: "low",
        progressPercent: 50,
        completedSteps: 1,
        totalSteps: 2,
      },
    ],
  },
];
