import type { ProductionProcess } from "@/features/production/production.types";

export const defaultProductionProcesses: ProductionProcess[] = [
  {
    id: "design-review",
    name: "Design Review",
    description: "Validate scans, margins, and restoration plan before release.",
    owner: "CAD team",
    capacity: 12,
    targetHours: 4,
    queue: [
      {
        id: "queue-1",
        caseCode: "CASE-1001",
        patientName: "Maria Oliveira",
        customerName: "Bright Smile customer",
        dueDate: "2026-06-10",
        restoration: "Zirconia crown",
        assignee: "Ana",
        priority: "rush",
        notes: "Check margin on distal side.",
      },
      {
        id: "queue-2",
        caseCode: "CASE-1002",
        patientName: "Lucas Mendes",
        customerName: "Downtown Dental",
        dueDate: "2026-06-11",
        restoration: "Implant abutment",
        assignee: "Roberto",
        priority: "standard",
      },
    ],
  },
  {
    id: "model-prep",
    name: "Model Prep",
    description: "Print, inspect, and prepare physical models for finishing.",
    owner: "Model room",
    capacity: 9,
    targetHours: 8,
    queue: [
      {
        id: "queue-3",
        caseCode: "CASE-1003",
        patientName: "Helena Costa",
        customerName: "Northside Dentistry",
        dueDate: "2026-06-12",
        restoration: "Three-unit bridge",
        assignee: "Julia",
        priority: "standard",
      },
    ],
  },
  {
    id: "ceramic-finish",
    name: "Ceramic Finish",
    description: "Layering, stain, glaze, and final esthetic inspection.",
    owner: "Ceramics",
    capacity: 7,
    targetHours: 12,
    queue: [
      {
        id: "queue-4",
        caseCode: "CASE-1004",
        patientName: "Rafael Lima",
        customerName: "Apex Dental Group",
        dueDate: "2026-06-09",
        restoration: "Veneer set",
        assignee: "Carla",
        priority: "rush",
        notes: "Shade match photo attached in case record.",
      },
      {
        id: "queue-5",
        caseCode: "CASE-1005",
        patientName: "Sofia Martins",
        customerName: "Bright Smile customer",
        dueDate: "2026-06-13",
        restoration: "E.max crown",
        assignee: "Diego",
        priority: "standard",
      },
      {
        id: "queue-6",
        caseCode: "CASE-1006",
        patientName: "Bruno Rocha",
        customerName: "Downtown Dental",
        dueDate: "2026-06-14",
        restoration: "Night guard",
        assignee: "Carla",
        priority: "standard",
      },
    ],
  },
];
